services:
  neofreq:
    build: .
    container_name: neofreq
    restart: unless-stopped
    ports:
      - "8085:80"
    networks:
      - freqtrade_default

networks:
  freqtrade_default:
    external: true
